---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# MLBlogos

<!-- badges: start -->
<!-- badges: end -->

The goal of MLBlogos is to provide small (150 x 100) logos for the teams in Major League Baseball
(from the 2021 season).
A possible use is to create tables and graphs of Teams data from the [Lahman package](https://github.com/cdalzell/Lahman).

## Installation

You can install the development version of MLBlogos from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("friendly/MLBlogos")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(MLBlogos)

## Information about the logos is contained in the `Logos` data set. The file name of each logo (in PNG format) is contained in the
## `png` variable. `TeamID` is the matching variable in `Lahman::Teams`.
data(Logos)
knitr::kable(Logos[1:15, 1:4])
```

